#spring
spring:
  application:
    name: springboot-elasticsearch
  data:
    elasticsearch:
      ip: 127.0.0.1
      port: 9200
      scheme: http
#      index: es_user_index
#      type: doc
server:
  port: 8092

